#!/bin/bash

export PORT=5000
export APP_URL='http://localhost:5000'
export GITHUB_OAUTH_KEY='mygithubkey'
export GITHUB_OAUTH_SECRET='mygithubsecret'
export DROPBOX_KEY='mydropboxkey'

exec gulp devel
